name: the_5th_real_estate
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.4.6
  image_picker: ^1.2.3
  go_router: ^17.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/background.jpeg
    - assets/image/bait_elwatan.webp
    - assets/image/gardenia.webp

 