// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKsjPqjRTxJ2usZPZqUMuoDL9iP8Tj76A',
    appId: '1:200241901984:web:e4db36925ae15e382434c5',
    messagingSenderId: '200241901984',
    projectId: 'real-estate-app-7031d',
    authDomain: 'real-estate-app-7031d.firebaseapp.com',
    storageBucket: 'real-estate-app-7031d.firebasestorage.app',
    measurementId: 'G-M0BE9Z89SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ7dz9eB3__5ZpdDg9MtYXOUrxq8gj4qE',
    appId: '1:200241901984:android:edffca4a5e8dc7aa2434c5',
    messagingSenderId: '200241901984',
    projectId: 'real-estate-app-7031d',
    storageBucket: 'real-estate-app-7031d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz8bZRVlgGgknrDjRNJaFDqYwuYkvtjn8',
    appId: '1:200241901984:ios:570b83b2c748cb5e2434c5',
    messagingSenderId: '200241901984',
    projectId: 'real-estate-app-7031d',
    storageBucket: 'real-estate-app-7031d.firebasestorage.app',
    iosClientId: '200241901984-m1rce7olerk1rtiohjvhg0lhu8sd97t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.the5thRealEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz8bZRVlgGgknrDjRNJaFDqYwuYkvtjn8',
    appId: '1:200241901984:ios:570b83b2c748cb5e2434c5',
    messagingSenderId: '200241901984',
    projectId: 'real-estate-app-7031d',
    storageBucket: 'real-estate-app-7031d.firebasestorage.app',
    iosClientId: '200241901984-m1rce7olerk1rtiohjvhg0lhu8sd97t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.the5thRealEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKsjPqjRTxJ2usZPZqUMuoDL9iP8Tj76A',
    appId: '1:200241901984:web:a91de0d009add3b72434c5',
    messagingSenderId: '200241901984',
    projectId: 'real-estate-app-7031d',
    authDomain: 'real-estate-app-7031d.firebaseapp.com',
    storageBucket: 'real-estate-app-7031d.firebasestorage.app',
    measurementId: 'G-H7VM0C8LNQ',
  );
}
